# Generated by Django 5.2.7 on 2025-10-31 22:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this organization",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Company name", max_length=255)),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Company website domain (e.g., 'acme.com')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("technology", "Technology"),
                            ("finance", "Finance"),
                            ("healthcare", "Healthcare"),
                            ("manufacturing", "Manufacturing"),
                            ("retail", "Retail"),
                            ("education", "Education"),
                            ("real_estate", "Real Estate"),
                            ("consulting", "Consulting"),
                            ("media", "Media & Entertainment"),
                            ("transportation", "Transportation"),
                            ("energy", "Energy"),
                            ("telecommunications", "Telecommunications"),
                            ("hospitality", "Hospitality"),
                            ("other", "Other"),
                        ],
                        help_text="Company industry",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "employee_count",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-10", "1-10 employees"),
                            ("11-50", "11-50 employees"),
                            ("51-200", "51-200 employees"),
                            ("201-500", "201-500 employees"),
                            ("501-1000", "501-1000 employees"),
                            ("1001-5000", "1001-5000 employees"),
                            ("5001+", "5001+ employees"),
                        ],
                        help_text="Number of employees",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual revenue in USD",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Main phone number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="General contact email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Company website", null=True),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True,
                        help_text="Street address",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        help_text="Suite, floor, etc.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City", max_length=100, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="State/Province",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="ZIP/Postal code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Country", max_length=100, null=True
                    ),
                ),
                (
                    "lifecycle_stage",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("qualified", "Qualified"),
                            ("opportunity", "Opportunity"),
                            ("customer", "Customer"),
                            ("evangelist", "Evangelist"),
                            ("other", "Other"),
                        ],
                        default="lead",
                        help_text="Where this organization is in the sales process",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this organization active?"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, help_text="LinkedIn company page", null=True
                    ),
                ),
                (
                    "twitter_handle",
                    models.CharField(
                        blank=True,
                        help_text="Twitter/X handle (without @)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="General notes about this organization",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this organization was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this organization was last updated",
                    ),
                ),
                (
                    "last_contacted",
                    models.DateTimeField(
                        blank=True,
                        help_text="When we last contacted this organization",
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who owns/manages this organization",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this contact",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Contact's first name", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Contact's last name", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary email address", max_length=254, unique=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary phone number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        help_text="Mobile phone number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        help_text="Job title (e.g., 'CEO', 'Marketing Manager')",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "lifecycle_stage",
                    models.CharField(
                        choices=[
                            ("subscriber", "Subscriber"),
                            ("lead", "Lead"),
                            ("marketing_qualified", "Marketing Qualified Lead (MQL)"),
                            ("sales_qualified", "Sales Qualified Lead (SQL)"),
                            ("opportunity", "Opportunity"),
                            ("customer", "Customer"),
                            ("evangelist", "Evangelist"),
                            ("other", "Other"),
                        ],
                        default="lead",
                        help_text="Where this contact is in the sales process",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this contact active? Inactive contacts are hidden from most views",
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True,
                        help_text="Street address",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        help_text="Apartment, suite, etc.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City", max_length=100, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="State/Province",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="ZIP/Postal code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Country", max_length=100, null=True
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, help_text="LinkedIn profile URL", null=True
                    ),
                ),
                (
                    "twitter_handle",
                    models.CharField(
                        blank=True,
                        help_text="Twitter/X handle (without @)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Personal website", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="General notes about this contact",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this contact was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this contact was last updated"
                    ),
                ),
                (
                    "last_contacted",
                    models.DateTimeField(
                        blank=True,
                        help_text="When we last contacted this person",
                        null=True,
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("website", "Website"),
                            ("referral", "Referral"),
                            ("linkedin", "LinkedIn"),
                            ("email_campaign", "Email Campaign"),
                            ("event", "Event/Conference"),
                            ("cold_outreach", "Cold Outreach"),
                            ("partner", "Partner"),
                            ("other", "Other"),
                        ],
                        help_text="How did this contact find us?",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who owns/manages this contact",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Company this contact works for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="crm.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "db_table": "contacts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["name"], name="organizatio_name_5cd1d4_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["domain"], name="organizatio_domain_edc3a8_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["industry"], name="organizatio_industr_24ff5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["lifecycle_stage"], name="organizatio_lifecyc_0711d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["owner"], name="organizatio_owner_i_0051c7_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["-created_at"], name="organizatio_created_7f4ee3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["email"], name="contacts_email_2eb381_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["last_name", "first_name"], name="contacts_last_na_ace8a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["lifecycle_stage"], name="contacts_lifecyc_c88ad0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["owner"], name="contacts_owner_i_f913b7_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["-created_at"], name="contacts_created_994491_idx"
            ),
        ),
    ]
