# Generated by Django 5.2.7 on 2025-10-31 23:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this deal",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Deal name (e.g., 'Enterprise License Q4 2025')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the deal",
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Deal value in USD", max_digits=15
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (USD, EUR, GBP, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("qualified", "Qualified"),
                            ("meeting_scheduled", "Meeting Scheduled"),
                            ("proposal_sent", "Proposal Sent"),
                            ("negotiation", "Negotiation"),
                            ("closed_won", "Closed Won"),
                            ("closed_lost", "Closed Lost"),
                        ],
                        default="lead",
                        help_text="Current stage in the sales pipeline",
                        max_length=50,
                    ),
                ),
                (
                    "probability",
                    models.IntegerField(
                        default=0, help_text="Win probability (0-100%)"
                    ),
                ),
                (
                    "expected_close_date",
                    models.DateField(
                        blank=True,
                        help_text="When we expect to close this deal",
                        null=True,
                    ),
                ),
                (
                    "actual_close_date",
                    models.DateField(
                        blank=True,
                        help_text="When the deal was actually closed",
                        null=True,
                    ),
                ),
                (
                    "loss_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("price", "Price Too High"),
                            ("competitor", "Lost to Competitor"),
                            ("timing", "Bad Timing"),
                            ("budget", "No Budget"),
                            ("no_decision", "No Decision"),
                            ("requirements", "Requirements Not Met"),
                            ("other", "Other"),
                        ],
                        help_text="Why was this deal lost?",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "loss_reason_detail",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about why deal was lost",
                        null=True,
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("website", "Website"),
                            ("referral", "Referral"),
                            ("linkedin", "LinkedIn"),
                            ("email_campaign", "Email Campaign"),
                            ("event", "Event/Conference"),
                            ("cold_outreach", "Cold Outreach"),
                            ("partner", "Partner"),
                            ("inbound", "Inbound"),
                            ("other", "Other"),
                        ],
                        help_text="How did this opportunity originate?",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "next_step",
                    models.TextField(
                        blank=True,
                        help_text="What's the next action for this deal?",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this deal was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this deal was last updated"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary contact for this deal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="crm.contact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Company this deal is with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="crm.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Sales rep who owns this deal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_deals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal",
                "verbose_name_plural": "Deals",
                "db_table": "deals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["stage"], name="deals_stage_e4369d_idx"),
                    models.Index(
                        fields=["organization"], name="deals_organiz_969d95_idx"
                    ),
                    models.Index(fields=["owner"], name="deals_owner_i_e6076f_idx"),
                    models.Index(
                        fields=["expected_close_date"], name="deals_expecte_53925b_idx"
                    ),
                    models.Index(fields=["-amount"], name="deals_amount_729edc_idx"),
                    models.Index(
                        fields=["-created_at"], name="deals_created_34f492_idx"
                    ),
                ],
            },
        ),
    ]
