# Generated by Django 5.2.7 on 2025-11-01 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this tenant",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Display name of the company (e.g., 'Acme Corporation')",
                        max_length=255,
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        help_text="PostgreSQL schema name (e.g., 'acme_corp')",
                        max_length=63,
                        unique=True,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="Subdomain for this tenant (e.g., 'acme' for acme.syntroph.com)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "owner_email",
                    models.EmailField(
                        help_text="Email of the person who signed up (becomes first admin)",
                        max_length=254,
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free Tier"),
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        help_text="Current subscription plan",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this tenant's account is active",
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        default=5,
                        help_text="Maximum number of users allowed (based on subscription)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this tenant was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this tenant was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["domain"], name="tenants_domain_726e44_idx"),
                    models.Index(
                        fields=["schema_name"], name="tenants_schema__8b4afe_idx"
                    ),
                ],
            },
        ),
    ]
