# Generated by Django 5.2.7 on 2025-10-31 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this tenant",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Company/Organization name (e.g., 'Acme Corporation')",
                        max_length=255,
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        help_text="Database schema name (e.g., 'tenant_acme_corp'). Must be unique.",
                        max_length=63,
                        unique=True,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Custom domain for this tenant (e.g., 'acme.syntroph.com')",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this tenant active? Inactive tenants cannot access the system.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this tenant was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this tenant was last updated"
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        help_text="Subscription plan tier",
                        max_length=50,
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        default=5,
                        help_text="Maximum number of users allowed for this tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this membership",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Administrator"),
                            ("manager", "Manager"),
                            ("user", "User"),
                            ("guest", "Guest"),
                        ],
                        default="user",
                        help_text="User's role in this tenant",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this membership active? Inactive members cannot access the tenant.",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the user joined this tenant"
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who invited this member",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant this user belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who is a member of the tenant",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Membership",
                "verbose_name_plural": "Tenant Memberships",
                "db_table": "tenant_memberships",
                "ordering": ["-joined_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "tenant"], name="tenant_memb_user_id_7fcafa_idx"
                    ),
                    models.Index(
                        fields=["tenant", "role"], name="tenant_memb_tenant__9ab271_idx"
                    ),
                ],
                "unique_together": {("user", "tenant")},
            },
        ),
    ]
