# Generated by Django 5.2.7 on 2025-10-31 23:09

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tenant_tenantmembership"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.UserManager()),
            ],
        ),
    ]
