"""
Django Migrations Package

This folder contains database migration files that Django creates automatically.

What are migrations?
- Python files that describe changes to your database schema
- Generated by: python manage.py makemigrations
- Applied by: python manage.py migrate

Migration files track:
- Creating new tables
- Adding/removing columns
- Changing data types
- Creating indexes, constraints, etc.

Every Django app MUST have a migrations folder with __init__.py to track database changes.
"""
